[tool.poetry]
name = "geotoimage"
version = "0.1.0"
description = ""
authors = ["m <mmailm@mail.ru>"]

[tool.poetry.dependencies]
python = "3.6"
mercantile = "^1.0"
pycairo = "^1.17"
Pillow = "^5.2"
cairocffi = "^0.8.1"

[tool.poetry.dev-dependencies]
